#!/bin/sh
/bin/rm -rf /root/bin
/bin/mkdir /root/bin

/bin/cp -f memstats /root/bin/
/bin/cp -f memstats_bigstart /etc/bigstart/scripts/memstats

echo "start memstats service..."
/usr/bin/bigstart add memstats


echo "wait 10 second to check service status..."
sleep 10 

/usr/bin/bigstart status memstats
